"""add_action_key_to_catalog_items

Revision ID: 35cab2f47aed
Revises: f5a6b7c8d9e0
Create Date: 2026-04-24 19:53:08.403431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35cab2f47aed'
down_revision: Union[str, Sequence[str], None] = 'f5a6b7c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_items_category'), table_name='catalog_items')
    op.drop_index(op.f('ix_execution_logs_workflow_id'), table_name='execution_logs')
    op.alter_column('executions', 'initial_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('executions', 'current_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('executions', 'error_details',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('workflows', 'webhook_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('workflows', 'workflow_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_workflows_webhook_token'), table_name='workflows')
    op.create_unique_constraint(None, 'workflows', ['webhook_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='unique')
    op.create_index(op.f('ix_workflows_webhook_token'), 'workflows', ['webhook_token'], unique=True)
    op.alter_column('workflows', 'workflow_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('workflows', 'webhook_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('executions', 'error_details',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('executions', 'current_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('executions', 'initial_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_execution_logs_workflow_id'), 'execution_logs', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_catalog_items_category'), 'catalog_items', ['category'], unique=False)
    # ### end Alembic commands ###
